import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyState,validateState,mergeState} from '../public/domain.mjs';
import {day} from '../public/dates.mjs';
import {newStudio,createWriting,freezeOriginal,createFeedbackRequest,acceptWritingReport,saveRewrite,addReading,writingAnalytics,comparisonKey,writingCounts,diffWords,RUBRICS} from '../public/studio-domain.mjs';
import {buildWritingPrompt,parseWritingReport} from '../public/studio-handoff.mjs';
const now=new Date('2026-10-09T03:00:00Z');
function fixture(language='en',options={}){const studio=newStudio(),w=createWriting(studio,{language,now,...options});w.draft=language==='en'?'I was worried about the sudden change. I wanted to rest at home.':'날씨가 추워지면서 몸이 피곤했다. 그래서 저녁에는 집에서 쉬었다.';w.provenance='independent';studio.writings.push(w);const request=createFeedbackRequest(w,'original',options.now||now);return {studio,w,request};}
function report(w,request){return {format:'english-basket-writing-report-v1',writingId:w.id,requestId:request.id,phase:request.phase,language:w.language,level:w.level,difficulty:w.difficulty,rubricVersion:RUBRICS[w.language].version,confidence:'high',strengths:['감정과 행동을 연결했어요.'],improvements:[{area:RUBRICS[w.language].areas[0][0],original:'worried',suggestion:'시제를 확인해 보세요.',reason:'지난 일을 설명해요.'}],flow:'생각과 이유가 이어져요.',errors:[],revisedExample:w.original,scores:Object.fromEntries(RUBRICS[w.language].areas.map(([id,,max])=>[id,id==='basket'?0:max-2])),usedExpressionIds:[]};}
test('old v1 backups retain expressions/reviews/sessions; studio extension is optional',()=>{const old={...emptyState(),reviews:[{id:'r',answer:'my English'}]};delete old.studio;validateState(old);const merged=mergeState(emptyState(),old);assert.deepEqual(merged.reviews,old.reviews);assert.equal(merged.studio.version,1);});
test('first text stays immutable through rewrite, error, repeated saves and feedback',()=>{const {studio,w,request}=fixture();const original=w.original;w.draft='changed';freezeOriginal(w);w.rewrite='I felt worried yesterday, so I decided to rest.';saveRewrite(w,'own-rewrite',true);saveRewrite(w,'own-rewrite',true);assert.equal(w.original,original);assert.equal(w.revisions.length,1);const evaluation=parseWritingReport('```json\n'+JSON.stringify(report(w,request))+'\n```',w,request);acceptWritingReport(studio,w,request,evaluation,now);acceptWritingReport(studio,w,request,evaluation,now);assert.equal(studio.evaluations.length,1);assert.equal(w.original,original);});
test('feedback binds writing, request, phase, language, level, difficulty and rubric',()=>{const {w,request}=fixture();const valid=report(w,request);for(const [key,value]of Object.entries({writingId:'other',requestId:'other',phase:'rewrite',language:'ko',level:2,difficulty:'stretch',rubricVersion:'old'}))assert.throws(()=>parseWritingReport(JSON.stringify({...valid,[key]:value}),w,request));assert.match(buildWritingPrompt(w,request),/처음|직접 작성/);assert.match(buildWritingPrompt(w,request),/2~3개/);assert.match(buildWritingPrompt(w,request),/독립 능력/);});
test('score limits, excess corrections, unknown expressions and malformed reports rejected',()=>{const {w,request}=fixture(),valid=report(w,request);assert.throws(()=>parseWritingReport('broken',w,request));assert.throws(()=>parseWritingReport(JSON.stringify({...valid,scores:{...valid.scores,grammar:26}}),w,request));assert.throws(()=>parseWritingReport(JSON.stringify({...valid,usedExpressionIds:['unknown']}),w,request));assert.throws(()=>parseWritingReport(JSON.stringify({...valid,improvements:Array(4).fill(valid.improvements[0])}),w,request));});
test('rewritten GPT example is never eligible as independent growth',()=>{const {studio,w}=fixture();w.rewrite=w.original;saveRewrite(w,'ai-example');const req=createFeedbackRequest(w,'rewrite',now);acceptWritingReport(studio,w,req,parseWritingReport(JSON.stringify(report(w,req)),w,req),now);const a=writingAnalytics(studio,{now});assert.ok(a.points.every(p=>p.score===null));assert.equal(studio.evaluations[0].provenance,'assisted-rewrite');});
test('short samples downgrade confidence; altered rewrite rejects stale evaluation',()=>{const {studio,w}=fixture();w.rewrite='OK.';const req=createFeedbackRequest(w,'rewrite',now),value=parseWritingReport(JSON.stringify(report(w,req)),w,req);acceptWritingReport(studio,w,req,value,now);assert.equal(studio.evaluations[0].confidence,'low');const req2=createFeedbackRequest(w,'rewrite',new Date(now.getTime()+1000));w.rewrite='Changed after sending.';assert.throws(()=>acceptWritingReport(newStudio(),w,req2,value));});
test('weekly topics change with constant conditions, one attempt per week, no helped first text',()=>{const {studio,w}=fixture('en',{type:'weekly',level:2});assert.equal(createWriting(studio,{type:'weekly',now}).id,w.id);const next=createWriting(studio,{type:'weekly',level:6,difficulty:'stretch',now:new Date('2026-10-16T03:00:00Z')});assert.notEqual(next.topic,w.topic);assert.equal(next.level,2);assert.deepEqual(next.target,w.target);next.draft='My writing';next.provenance='assisted';assert.throws(()=>freezeOriginal(next));});
test('different languages, levels, difficulty and rubric never share comparison groups',()=>{const {studio,w,request}=fixture();acceptWritingReport(studio,w,request,parseWritingReport(JSON.stringify(report(w,request)),w,request),now);for(const opts of [{language:'ko'},{level:3},{difficulty:'stretch'}]){const other=fixture(opts.language||'en',opts);studio.writings.push(other.w);acceptWritingReport(studio,other.w,other.request,parseWritingReport(JSON.stringify(report(other.w,other.request)),other.w,other.request),now);}const a=writingAnalytics(studio,{key:comparisonKey(w),now});assert.equal(a.groups.length,3);assert.equal(a.points.at(-1).evaluations.length,1);assert.equal(a.weeklyChange,null);assert.equal(writingAnalytics(studio,{language:'ko',now}).groups.length,1);});
test('seven-day graph distinguishes blank, draft/ungraded, low-confidence and scored days',()=>{const s=newStudio();for(let i=0;i<4;i++){const time=new Date(now.getTime()-(3-i)*86400000),f=fixture('en',{now:time});s.writings.push(f.w);if(i===1||i===3){const value=parseWritingReport(JSON.stringify(report(f.w,f.request)),f.w,f.request);if(i===1)value.confidence='low';acceptWritingReport(s,f.w,f.request,value,time);}}const a=writingAnalytics(s,{now});assert.deepEqual(a.points.slice(-4).map(p=>p.state),['ungraded','low-confidence','ungraded','evaluated']);assert.equal(a.points[0].state,'empty');assert.equal(writingAnalytics(s,{days:90,now}).points.length,90);});
test('reading captures only user input and deduplicates identical excerpts',()=>{const s=newStudio(),values={source:'NIV Bible',book:'User-supplied reference',location:'User page',original:'Short user supplied sentence.',expression:'be worried',meaning:'걱정하다',memo:'my note'};const r=addReading(s,values,now);s.readings.push(r);assert.equal(addReading(s,values,now).id,r.id);assert.equal(r.original,values.original);assert.throws(()=>addReading(s,{...values,original:'x'.repeat(3001)}));});
test('conflicting backup drafts preserved in separate copies and reimport is idempotent',()=>{const a=emptyState(),{studio,w,request}=fixture();a.studio=studio;acceptWritingReport(studio,w,request,parseWritingReport(JSON.stringify(report(w,request)),w,request),now);const b=structuredClone(a);b.studio.writings[0].rewrite='different backup draft';const merged=mergeState(a,b);assert.equal(merged.studio.writings.length,2);assert.equal(merged.studio.evaluations.length,2);assert.equal(merged.studio.writings[0].rewrite,'');assert.equal(merged.studio.writings[1].rewrite,'different backup draft');validateState(merged);assert.equal(mergeState(merged,b).studio.writings.length,2);});
test('counts and comparison preserve multiline English/Korean without exposing markup',()=>{assert.equal(writingCounts('One sentence. Two sentences!','en').sentences,2);assert.equal(writingCounts('오늘은 쉬었다.\n내일은 걸어야겠다.','ko').sentences,2);assert.ok(diffWords('I am tired.','I was tired.').some(p=>p.text==='was'&&p.changed));assert.equal(day(now),'2026-10-09');});
test('import cannot forge comparison conditions or relabel rewrite as independent',()=>{const s=emptyState(),{studio,w,request}=fixture();s.studio=studio;acceptWritingReport(studio,w,request,parseWritingReport(JSON.stringify(report(w,request)),w,request),now);for(const patch of [{key:'forged'},{level:6},{provenance:'assisted-rewrite'},{evaluatedText:'different text'}]){const tampered=structuredClone(s);Object.assign(tampered.studio.evaluations[0],patch);assert.throws(()=>validateState(tampered));}});
